// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenCamera
void ui_ScreenCamera_screen_init(void);
extern lv_obj_t * ui_ScreenCamera;
extern lv_obj_t * ui_PixelGrid;
extern lv_obj_t * ui_Pixel1;
extern lv_obj_t * ui_Pixel2;
extern lv_obj_t * ui_Pixel3;
extern lv_obj_t * ui_Pixel4;
extern lv_obj_t * ui_Pixel5;
extern lv_obj_t * ui_Pixel6;
extern lv_obj_t * ui_Pixel7;
extern lv_obj_t * ui_Pixel8;
extern lv_obj_t * ui_Pixel9;
extern lv_obj_t * ui_Pixel10;
extern lv_obj_t * ui_Pixel11;
extern lv_obj_t * ui_Pixel12;
extern lv_obj_t * ui_Pixel13;
extern lv_obj_t * ui_Pixel14;
extern lv_obj_t * ui_Pixel15;
extern lv_obj_t * ui_Pixel16;
extern lv_obj_t * ui_Pixel17;
extern lv_obj_t * ui_Pixel18;
extern lv_obj_t * ui_Pixel19;
extern lv_obj_t * ui_Pixel20;
extern lv_obj_t * ui_Pixel21;
extern lv_obj_t * ui_Pixel22;
extern lv_obj_t * ui_Pixel23;
extern lv_obj_t * ui_Pixel24;
extern lv_obj_t * ui_Pixel25;
extern lv_obj_t * ui_Pixel26;
extern lv_obj_t * ui_Pixel27;
extern lv_obj_t * ui_Pixel28;
extern lv_obj_t * ui_Pixel29;
extern lv_obj_t * ui_Pixel30;
extern lv_obj_t * ui_Pixel31;
extern lv_obj_t * ui_Pixel32;
extern lv_obj_t * ui_Pixel33;
extern lv_obj_t * ui_Pixel34;
extern lv_obj_t * ui_Pixel35;
extern lv_obj_t * ui_Pixel36;
extern lv_obj_t * ui_Pixel37;
extern lv_obj_t * ui_Pixel38;
extern lv_obj_t * ui_Pixel39;
extern lv_obj_t * ui_Pixel40;
extern lv_obj_t * ui_Pixel41;
extern lv_obj_t * ui_Pixel42;
extern lv_obj_t * ui_Pixel43;
extern lv_obj_t * ui_Pixel44;
extern lv_obj_t * ui_Pixel45;
extern lv_obj_t * ui_Pixel46;
extern lv_obj_t * ui_Pixel47;
extern lv_obj_t * ui_Pixel48;
extern lv_obj_t * ui_Pixel49;
extern lv_obj_t * ui_Pixel50;
extern lv_obj_t * ui_Pixel51;
extern lv_obj_t * ui_Pixel52;
extern lv_obj_t * ui_Pixel53;
extern lv_obj_t * ui_Pixel54;
extern lv_obj_t * ui_Pixel55;
extern lv_obj_t * ui_Pixel56;
extern lv_obj_t * ui_Pixel57;
extern lv_obj_t * ui_Pixel58;
extern lv_obj_t * ui_Pixel59;
extern lv_obj_t * ui_Pixel60;
extern lv_obj_t * ui_Pixel61;
extern lv_obj_t * ui_Pixel62;
extern lv_obj_t * ui_Pixel63;
extern lv_obj_t * ui_Pixel64;
extern lv_obj_t * ui_TitleCamera;
// SCREEN: ui_ScreenSensors
void ui_ScreenSensors_screen_init(void);
extern lv_obj_t * ui_ScreenSensors;
extern lv_obj_t * ui_TitleSensorValues;
extern lv_obj_t * ui_SensorValueLabels;
extern lv_obj_t * ui_SurfaceTempText;
extern lv_obj_t * ui_SurfaceTempDisplay;
extern lv_obj_t * ui_Value;
extern lv_obj_t * ui_Unit;
extern lv_obj_t * ui_AirTempText;
extern lv_obj_t * ui_AirTempDisplay;
extern lv_obj_t * ui_Value1;
extern lv_obj_t * ui_Unit1;
extern lv_obj_t * ui_AirHumText;
extern lv_obj_t * ui_AirHumDisplay;
extern lv_obj_t * ui_Value2;
extern lv_obj_t * ui_Unit2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_location2_png);    // assets/location2.png



LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
