// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenPopUp_screen_init(void)
{
    ui_ScreenPopUp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPopUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPopUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPopUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPopUp = lv_obj_create(ui_ScreenPopUp);
    lv_obj_set_width(ui_PanelPopUp, 380);
    lv_obj_set_height(ui_PanelPopUp, 330);
    lv_obj_set_align(ui_PanelPopUp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPopUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCalibration = lv_label_create(ui_PanelPopUp);
    lv_obj_set_width(ui_LabelCalibration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCalibration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCalibration, 0);
    lv_obj_set_y(ui_LabelCalibration, -5);
    lv_obj_set_align(ui_LabelCalibration, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelCalibration, "Calibration");
    lv_obj_set_style_text_align(ui_LabelCalibration, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCalibration, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibOption = lv_dropdown_create(ui_PanelPopUp);
    lv_dropdown_set_options(ui_CalibOption, "Enter value manually");
    lv_obj_set_width(ui_CalibOption, 300);
    lv_obj_set_height(ui_CalibOption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibOption, 0);
    lv_obj_set_y(ui_CalibOption, 70);
    lv_obj_set_align(ui_CalibOption, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_CalibOption, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_CalibOption, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalibOption, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalibOption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_CalibOption), &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_CalibOption), &lv_font_montserrat_18,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ValueCalib = lv_textarea_create(ui_PanelPopUp);
    lv_obj_set_width(ui_ValueCalib, 100);
    lv_obj_set_height(ui_ValueCalib, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueCalib, 0);
    lv_obj_set_y(ui_ValueCalib, 150);
    lv_obj_set_align(ui_ValueCalib, LV_ALIGN_TOP_RIGHT);
    lv_textarea_set_max_length(ui_ValueCalib, 5);
    lv_textarea_set_placeholder_text(ui_ValueCalib, "20.0");
    lv_textarea_set_one_line(ui_ValueCalib, true);
    lv_obj_add_state(ui_ValueCalib, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_font(ui_ValueCalib, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ValueNumpad = lv_keyboard_create(ui_PanelPopUp);
    lv_keyboard_set_mode(ui_ValueNumpad, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_ValueNumpad, 240);
    lv_obj_set_height(ui_ValueNumpad, 180);
    lv_obj_set_x(ui_ValueNumpad, -10);
    lv_obj_set_y(ui_ValueNumpad, 10);
    lv_obj_set_align(ui_ValueNumpad, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_bg_color(ui_ValueNumpad, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ValueNumpad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ValueNumpad, lv_color_hex(0x41444A), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_ValueNumpad, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_bg_color(ui_ValueNumpad, lv_color_hex(0x41444A), LV_PART_ITEMS | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_ValueNumpad, 255, LV_PART_ITEMS | LV_STATE_DISABLED);

    ui_ButtonCancel = lv_btn_create(ui_PanelPopUp);
    lv_obj_set_width(ui_ButtonCancel, 80);
    lv_obj_set_height(ui_ButtonCancel, 40);
    lv_obj_set_x(ui_ButtonCancel, -10);
    lv_obj_set_y(ui_ButtonCancel, -10);
    lv_obj_add_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCancel, lv_color_hex(0xFF5757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonCancel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCancel = lv_label_create(ui_ButtonCancel);
    lv_obj_set_width(ui_LabelCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCancel, "Cancel");

    ui_ButtonConfirm = lv_btn_create(ui_PanelPopUp);
    lv_obj_set_width(ui_ButtonConfirm, 80);
    lv_obj_set_height(ui_ButtonConfirm, 40);
    lv_obj_set_x(ui_ButtonConfirm, 10);
    lv_obj_set_y(ui_ButtonConfirm, -10);
    lv_obj_set_align(ui_ButtonConfirm, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ButtonConfirm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonConfirm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonConfirm, lv_color_hex(0x0D9900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonConfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonConfirm, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelConfirm = lv_label_create(ui_ButtonConfirm);
    lv_obj_set_width(ui_LabelConfirm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConfirm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelConfirm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConfirm, "Confirm");

    ui_LabelSource = lv_label_create(ui_PanelPopUp);
    lv_obj_set_width(ui_LabelSource, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSource, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSource, 0);
    lv_obj_set_y(ui_LabelSource, 40);
    lv_obj_set_align(ui_LabelSource, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelSource, "Choose calibration source:");
    lv_obj_set_style_text_font(ui_LabelSource, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInfo = lv_label_create(ui_PanelPopUp);
    lv_obj_set_width(ui_LabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInfo, 10);
    lv_obj_set_y(ui_LabelInfo, 210);
    lv_obj_set_align(ui_LabelInfo, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelInfo, "(Enter -1 to reset)");

    lv_keyboard_set_textarea(ui_ValueNumpad, ui_ValueCalib);

}
