// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenTime_screen_init(void)
{
    ui_ScreenTime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Date = lv_calendar_create(ui_ScreenTime);
    lv_calendar_set_today_date(ui_Date, 2025, 4, 1);
    lv_calendar_set_showed_date(ui_Date, 2025, 4);
    lv_obj_t * ui_Date_header = lv_calendar_header_arrow_create(ui_Date);
    lv_obj_set_width(ui_Date, 440);
    lv_obj_set_height(ui_Date, 280);
    lv_obj_set_x(ui_Date, 0);
    lv_obj_set_y(ui_Date, 50);
    lv_obj_set_align(ui_Date, LV_ALIGN_TOP_MID);

    ui_TitleTime = lv_label_create(ui_ScreenTime);
    lv_obj_set_width(ui_TitleTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleTime, 0);
    lv_obj_set_y(ui_TitleTime, 10);
    lv_obj_set_align(ui_TitleTime, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TitleTime, "Date and Time Settings");
    lv_obj_set_style_text_align(ui_TitleTime, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleTime, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSave = lv_btn_create(ui_ScreenTime);
    lv_obj_set_width(ui_ButtonSave, 100);
    lv_obj_set_height(ui_ButtonSave, 50);
    lv_obj_set_x(ui_ButtonSave, 150);
    lv_obj_set_y(ui_ButtonSave, -60);
    lv_obj_set_align(ui_ButtonSave, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ButtonSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SaveLabel = lv_label_create(ui_ButtonSave);
    lv_obj_set_width(ui_SaveLabel, 140);
    lv_obj_set_height(ui_SaveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SaveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabel, "Save");
    lv_obj_set_style_text_align(ui_SaveLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_obj_create(ui_ScreenTime);
    lv_obj_remove_style_all(ui_Time);
    lv_obj_set_width(ui_Time, 290);
    lv_obj_set_height(ui_Time, 130);
    lv_obj_set_x(ui_Time, -80);
    lv_obj_set_y(ui_Time, -20);
    lv_obj_set_align(ui_Time, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hours = lv_obj_create(ui_Time);
    lv_obj_remove_style_all(ui_Hours);
    lv_obj_set_width(ui_Hours, 130);
    lv_obj_set_height(ui_Hours, 130);
    lv_obj_set_x(ui_Hours, -80);
    lv_obj_set_y(ui_Hours, 0);
    lv_obj_set_align(ui_Hours, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Hours, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HoursSlider = lv_arc_create(ui_Hours);
    lv_obj_set_width(ui_HoursSlider, 120);
    lv_obj_set_height(ui_HoursSlider, 120);
    lv_obj_set_align(ui_HoursSlider, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_HoursSlider, 0, 23);
    lv_arc_set_value(ui_HoursSlider, 11);
    lv_arc_set_bg_angles(ui_HoursSlider, 270, 269);


    ui_HoursText = lv_label_create(ui_Hours);
    lv_obj_set_width(ui_HoursText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HoursText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HoursText, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_HoursText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HoursText, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minutes = lv_obj_create(ui_Time);
    lv_obj_remove_style_all(ui_Minutes);
    lv_obj_set_width(ui_Minutes, 130);
    lv_obj_set_height(ui_Minutes, 130);
    lv_obj_set_x(ui_Minutes, 80);
    lv_obj_set_y(ui_Minutes, 0);
    lv_obj_set_align(ui_Minutes, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Minutes, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinutesSlider = lv_arc_create(ui_Minutes);
    lv_obj_set_width(ui_MinutesSlider, 120);
    lv_obj_set_height(ui_MinutesSlider, 120);
    lv_obj_set_align(ui_MinutesSlider, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_MinutesSlider, 0, 59);
    lv_arc_set_value(ui_MinutesSlider, 30);
    lv_arc_set_bg_angles(ui_MinutesSlider, 270, 269);


    ui_MinutesText = lv_label_create(ui_Minutes);
    lv_obj_set_width(ui_MinutesText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinutesText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MinutesText, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_MinutesText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinutesText, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colon = lv_label_create(ui_Time);
    lv_obj_set_width(ui_Colon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Colon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Colon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Colon, ":");
    lv_obj_set_style_text_font(ui_Colon, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HoursSlider, ui_event_HoursSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MinutesSlider, ui_event_MinutesSlider, LV_EVENT_ALL, NULL);

}
