// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSensors_screen_init(void)
{
    ui_ScreenSensors = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSensors, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitleSensorValues = lv_label_create(ui_ScreenSensors);
    lv_obj_set_width(ui_TitleSensorValues, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleSensorValues, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleSensorValues, 0);
    lv_obj_set_y(ui_TitleSensorValues, 10);
    lv_obj_set_align(ui_TitleSensorValues, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TitleSensorValues, "Sensor Values");
    lv_obj_set_style_text_align(ui_TitleSensorValues, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleSensorValues, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorValueLabels = lv_obj_create(ui_ScreenSensors);
    lv_obj_remove_style_all(ui_SensorValueLabels);
    lv_obj_set_width(ui_SensorValueLabels, 400);
    lv_obj_set_height(ui_SensorValueLabels, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SensorValueLabels, 0);
    lv_obj_set_y(ui_SensorValueLabels, 20);
    lv_obj_set_align(ui_SensorValueLabels, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SensorValueLabels, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SensorValueLabels, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SensorValueLabels, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SurfaceTempText = lv_label_create(ui_SensorValueLabels);
    lv_obj_set_width(ui_SurfaceTempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SurfaceTempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SurfaceTempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SurfaceTempText, "Surface Temperature");
    lv_obj_set_style_text_font(ui_SurfaceTempText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SurfaceTempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SurfaceTempText, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SurfaceTempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SurfaceTempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SurfaceTempDisplay = lv_obj_create(ui_SensorValueLabels);
    lv_obj_remove_style_all(ui_SurfaceTempDisplay);
    lv_obj_set_width(ui_SurfaceTempDisplay, 200);
    lv_obj_set_height(ui_SurfaceTempDisplay, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SurfaceTempDisplay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SurfaceTempDisplay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SurfaceTempDisplay, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SurfaceTempDisplay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SurfaceTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SurfaceTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SurfaceTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SurfaceTempDisplay, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueST = lv_label_create(ui_SurfaceTempDisplay);
    lv_obj_set_width(ui_ValueST, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueST, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueST, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueST, "0.0");
    lv_obj_set_style_text_align(ui_ValueST, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueST, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ValueST, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ValueST, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ValueST, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ValueST, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnitST = lv_label_create(ui_SurfaceTempDisplay);
    lv_obj_set_width(ui_UnitST, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnitST, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UnitST, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UnitST, "°C");
    lv_obj_set_style_text_align(ui_UnitST, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UnitST, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_UnitST, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_UnitST, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_UnitST, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_UnitST, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirTempText = lv_label_create(ui_SensorValueLabels);
    lv_obj_set_width(ui_AirTempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirTempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AirTempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirTempText, "Air Temperature");
    lv_obj_set_style_text_font(ui_AirTempText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AirTempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AirTempText, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AirTempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AirTempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirTempDisplay = lv_obj_create(ui_SensorValueLabels);
    lv_obj_remove_style_all(ui_AirTempDisplay);
    lv_obj_set_width(ui_AirTempDisplay, 200);
    lv_obj_set_height(ui_AirTempDisplay, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_AirTempDisplay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AirTempDisplay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AirTempDisplay, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_AirTempDisplay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_AirTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AirTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AirTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AirTempDisplay, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueAT = lv_label_create(ui_AirTempDisplay);
    lv_obj_set_width(ui_ValueAT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueAT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueAT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueAT, "0.0");
    lv_obj_set_style_text_align(ui_ValueAT, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueAT, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ValueAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ValueAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ValueAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ValueAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnitAT = lv_label_create(ui_AirTempDisplay);
    lv_obj_set_width(ui_UnitAT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnitAT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UnitAT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UnitAT, "°C");
    lv_obj_set_style_text_align(ui_UnitAT, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UnitAT, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_UnitAT, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_UnitAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_UnitAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_UnitAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirHumText = lv_label_create(ui_SensorValueLabels);
    lv_obj_set_width(ui_AirHumText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirHumText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AirHumText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirHumText, "Air Humidity");
    lv_obj_set_style_text_font(ui_AirHumText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AirHumText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AirHumText, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AirHumText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AirHumText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirHumDisplay = lv_obj_create(ui_SensorValueLabels);
    lv_obj_remove_style_all(ui_AirHumDisplay);
    lv_obj_set_width(ui_AirHumDisplay, 200);
    lv_obj_set_height(ui_AirHumDisplay, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_AirHumDisplay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AirHumDisplay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AirHumDisplay, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_AirHumDisplay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_AirHumDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AirHumDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AirHumDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AirHumDisplay, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueAH = lv_label_create(ui_AirHumDisplay);
    lv_obj_set_width(ui_ValueAH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueAH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueAH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueAH, "100");
    lv_obj_set_style_text_align(ui_ValueAH, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueAH, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ValueAH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ValueAH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ValueAH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ValueAH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnitAH = lv_label_create(ui_AirHumDisplay);
    lv_obj_set_width(ui_UnitAH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnitAH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UnitAH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UnitAH, "%");
    lv_obj_set_style_text_align(ui_UnitAH, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UnitAH, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_UnitAH, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_UnitAH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_UnitAH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_UnitAH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MRTText = lv_label_create(ui_SensorValueLabels);
    lv_obj_set_width(ui_MRTText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MRTText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MRTText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MRTText, "Mean Radiant Temperature");
    lv_obj_set_style_text_font(ui_MRTText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MRTText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MRTText, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MRTText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MRTText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MRTDisplay = lv_obj_create(ui_SensorValueLabels);
    lv_obj_remove_style_all(ui_MRTDisplay);
    lv_obj_set_width(ui_MRTDisplay, 200);
    lv_obj_set_height(ui_MRTDisplay, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_MRTDisplay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MRTDisplay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MRTDisplay, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_MRTDisplay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_MRTDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MRTDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MRTDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MRTDisplay, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueMRT = lv_label_create(ui_MRTDisplay);
    lv_obj_set_width(ui_ValueMRT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueMRT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueMRT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueMRT, "0.0");
    lv_obj_set_style_text_align(ui_ValueMRT, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueMRT, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ValueMRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ValueMRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ValueMRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ValueMRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnitMRT = lv_label_create(ui_MRTDisplay);
    lv_obj_set_width(ui_UnitMRT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnitMRT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UnitMRT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UnitMRT, "°C");
    lv_obj_set_style_text_align(ui_UnitMRT, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UnitMRT, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_UnitMRT, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_UnitMRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_UnitMRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_UnitMRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}
