// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenLoRa_screen_init(void)
{
    ui_ScreenLoRa = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLoRa, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitleLoRa = lv_label_create(ui_ScreenLoRa);
    lv_obj_set_width(ui_TitleLoRa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleLoRa, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleLoRa, 0);
    lv_obj_set_y(ui_TitleLoRa, 10);
    lv_obj_set_align(ui_TitleLoRa, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TitleLoRa, "LoRaWAN Settings");
    lv_obj_set_style_text_align(ui_TitleLoRa, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleLoRa, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSettings = lv_obj_create(ui_ScreenLoRa);
    lv_obj_remove_style_all(ui_ContainerSettings);
    lv_obj_set_width(ui_ContainerSettings, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(ui_ContainerSettings, LV_SIZE_CONTENT);    /// 370
    lv_obj_set_x(ui_ContainerSettings, 0);
    lv_obj_set_y(ui_ContainerSettings, 70);
    lv_obj_set_align(ui_ContainerSettings, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ContainerSettings, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ContainerSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInterval = lv_label_create(ui_ContainerSettings);
    lv_obj_set_width(ui_LabelInterval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInterval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInterval, -57);
    lv_obj_set_y(ui_LabelInterval, 284);
    lv_obj_set_align(ui_LabelInterval, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInterval, "Send Interval (min)");
    lv_obj_set_style_text_font(ui_LabelInterval, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelInterval, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerInterval = lv_obj_create(ui_ContainerSettings);
    lv_obj_remove_style_all(ui_ContainerInterval);
    lv_obj_set_width(ui_ContainerInterval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContainerInterval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ContainerInterval, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerInterval, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerInterval, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerInterval, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerInterval, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerInterval, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMinus = lv_btn_create(ui_ContainerInterval);
    lv_obj_set_width(ui_ButtonMinus, 36);
    lv_obj_set_height(ui_ButtonMinus, 36);
    lv_obj_set_align(ui_ButtonMinus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonMinus, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueInterval = lv_spinbox_create(ui_ContainerInterval);
    lv_obj_set_width(ui_ValueInterval, 70);
    lv_obj_set_height(ui_ValueInterval, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_align(ui_ValueInterval, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ValueInterval, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_spinbox_set_digit_format(ui_ValueInterval, 2, 2);
    lv_spinbox_set_range(ui_ValueInterval, 1, 60);
    lv_spinbox_set_cursor_pos(ui_ValueInterval, 1 - 1);
    lv_spinbox_set_value(ui_ValueInterval, 5);
    lv_obj_set_style_border_width(ui_ValueInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ValueInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ValueInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ValueInterval, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ValueInterval, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ValueInterval, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueInterval, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ValueInterval, lv_color_hex(0x292831), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ValueInterval, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_ButtonPlus = lv_btn_create(ui_ContainerInterval);
    lv_obj_set_width(ui_ButtonPlus, 36);
    lv_obj_set_height(ui_ButtonPlus, 36);
    lv_obj_set_align(ui_ButtonPlus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonPlus, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDevEUI = lv_label_create(ui_ContainerSettings);
    lv_obj_set_width(ui_LabelDevEUI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDevEUI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDevEUI, -48);
    lv_obj_set_y(ui_LabelDevEUI, 5);
    lv_obj_set_align(ui_LabelDevEUI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDevEUI, "DevEUI");
    lv_obj_set_style_text_font(ui_LabelDevEUI, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDevEUI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDevEUI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDevEUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDevEUI, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueDevEUI = lv_label_create(ui_ContainerSettings);
    lv_obj_set_width(ui_ValueDevEUI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueDevEUI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueDevEUI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueDevEUI, "00:00:00:00:00:00:00:00");
    lv_obj_set_style_text_font(ui_ValueDevEUI, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelJoinEUI = lv_label_create(ui_ContainerSettings);
    lv_obj_set_width(ui_LabelJoinEUI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelJoinEUI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelJoinEUI, -48);
    lv_obj_set_y(ui_LabelJoinEUI, 5);
    lv_obj_set_align(ui_LabelJoinEUI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelJoinEUI, "JoinEUI");
    lv_obj_set_style_text_font(ui_LabelJoinEUI, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelJoinEUI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelJoinEUI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelJoinEUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelJoinEUI, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueJoinEUI = lv_label_create(ui_ContainerSettings);
    lv_obj_set_width(ui_ValueJoinEUI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueJoinEUI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueJoinEUI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueJoinEUI, "00:00:00:00:00:00:00:00");
    lv_obj_set_style_text_font(ui_ValueJoinEUI, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAppKey = lv_label_create(ui_ContainerSettings);
    lv_obj_set_width(ui_LabelAppKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAppKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAppKey, -48);
    lv_obj_set_y(ui_LabelAppKey, 5);
    lv_obj_set_align(ui_LabelAppKey, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAppKey, "AppKey");
    lv_obj_set_style_text_font(ui_LabelAppKey, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelAppKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelAppKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelAppKey, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelAppKey, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueAppKey = lv_label_create(ui_ContainerSettings);
    lv_obj_set_width(ui_ValueAppKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueAppKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueAppKey, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueAppKey, "00:00:00:00:00:00:00:00\n00:00:00:00:00:00:00:00");
    lv_obj_set_style_text_font(ui_ValueAppKey, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ValueAppKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ValueAppKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ValueAppKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ValueAppKey, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoin = lv_btn_create(ui_ContainerSettings);
    lv_obj_set_width(ui_ButtonJoin, 100);
    lv_obj_set_height(ui_ButtonJoin, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_ButtonJoin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_ButtonJoin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonJoin, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonMinus, ui_event_ButtonMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPlus, ui_event_ButtonPlus, LV_EVENT_ALL, NULL);

}
