// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSensors_screen_init(void)
{
    ui_ScreenSensors = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSensors, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitleSensorValues = lv_label_create(ui_ScreenSensors);
    lv_obj_set_width(ui_TitleSensorValues, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleSensorValues, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleSensorValues, 0);
    lv_obj_set_y(ui_TitleSensorValues, 10);
    lv_obj_set_align(ui_TitleSensorValues, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TitleSensorValues, "Sensor Values");
    lv_obj_set_style_text_align(ui_TitleSensorValues, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleSensorValues, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorValueLabels = lv_obj_create(ui_ScreenSensors);
    lv_obj_remove_style_all(ui_SensorValueLabels);
    lv_obj_set_width(ui_SensorValueLabels, 400);
    lv_obj_set_height(ui_SensorValueLabels, LV_SIZE_CONTENT);    /// 350
    lv_obj_set_x(ui_SensorValueLabels, 0);
    lv_obj_set_y(ui_SensorValueLabels, -20);
    lv_obj_set_align(ui_SensorValueLabels, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SensorValueLabels, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SensorValueLabels, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SensorValueLabels, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SurfaceTempText = lv_label_create(ui_SensorValueLabels);
    lv_obj_set_width(ui_SurfaceTempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SurfaceTempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SurfaceTempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SurfaceTempText, "Surface Temperature");
    lv_obj_set_style_text_font(ui_SurfaceTempText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SurfaceTempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SurfaceTempText, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SurfaceTempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SurfaceTempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SurfaceTempDisplay = lv_obj_create(ui_SensorValueLabels);
    lv_obj_remove_style_all(ui_SurfaceTempDisplay);
    lv_obj_set_width(ui_SurfaceTempDisplay, 200);
    lv_obj_set_height(ui_SurfaceTempDisplay, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SurfaceTempDisplay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SurfaceTempDisplay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SurfaceTempDisplay, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SurfaceTempDisplay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SurfaceTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SurfaceTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SurfaceTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SurfaceTempDisplay, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Value = lv_label_create(ui_SurfaceTempDisplay);
    lv_obj_set_width(ui_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Value, "0.0");
    lv_obj_set_style_text_align(ui_Value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Value, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Unit = lv_label_create(ui_SurfaceTempDisplay);
    lv_obj_set_width(ui_Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Unit, "°C");
    lv_obj_set_style_text_align(ui_Unit, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Unit, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Unit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirTempText = lv_label_create(ui_SensorValueLabels);
    lv_obj_set_width(ui_AirTempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirTempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AirTempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirTempText, "Air Temperature");
    lv_obj_set_style_text_font(ui_AirTempText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AirTempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AirTempText, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AirTempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AirTempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirTempDisplay = lv_obj_create(ui_SensorValueLabels);
    lv_obj_remove_style_all(ui_AirTempDisplay);
    lv_obj_set_width(ui_AirTempDisplay, 200);
    lv_obj_set_height(ui_AirTempDisplay, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_AirTempDisplay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AirTempDisplay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AirTempDisplay, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_AirTempDisplay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_AirTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AirTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AirTempDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AirTempDisplay, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Value1 = lv_label_create(ui_AirTempDisplay);
    lv_obj_set_width(ui_Value1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Value1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Value1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Value1, "0.0");
    lv_obj_set_style_text_align(ui_Value1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Value1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Value1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Value1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Value1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Value1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Unit1 = lv_label_create(ui_AirTempDisplay);
    lv_obj_set_width(ui_Unit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Unit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Unit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Unit1, "°C");
    lv_obj_set_style_text_align(ui_Unit1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Unit1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Unit1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Unit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Unit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Unit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirHumText = lv_label_create(ui_SensorValueLabels);
    lv_obj_set_width(ui_AirHumText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirHumText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AirHumText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirHumText, "Air Humidity");
    lv_obj_set_style_text_font(ui_AirHumText, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AirHumText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AirHumText, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AirHumText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AirHumText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirHumDisplay = lv_obj_create(ui_SensorValueLabels);
    lv_obj_remove_style_all(ui_AirHumDisplay);
    lv_obj_set_width(ui_AirHumDisplay, 200);
    lv_obj_set_height(ui_AirHumDisplay, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_AirHumDisplay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AirHumDisplay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AirHumDisplay, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_AirHumDisplay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_AirHumDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AirHumDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AirHumDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AirHumDisplay, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Value2 = lv_label_create(ui_AirHumDisplay);
    lv_obj_set_width(ui_Value2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Value2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Value2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Value2, "100");
    lv_obj_set_style_text_align(ui_Value2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Value2, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Value2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Value2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Value2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Value2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Unit2 = lv_label_create(ui_AirHumDisplay);
    lv_obj_set_width(ui_Unit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Unit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Unit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Unit2, "%");
    lv_obj_set_style_text_align(ui_Unit2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Unit2, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Unit2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Unit2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Unit2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Unit2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}
