// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenCamera_screen_init(void)
{
    ui_ScreenCamera = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PixelGrid = lv_obj_create(ui_ScreenCamera);
    lv_obj_remove_style_all(ui_PixelGrid);
    lv_obj_set_width(ui_PixelGrid, 400);
    lv_obj_set_height(ui_PixelGrid, 400);
    lv_obj_set_x(ui_PixelGrid, 0);
    lv_obj_set_y(ui_PixelGrid, -20);
    lv_obj_set_align(ui_PixelGrid, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_PixelGrid, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PixelGrid, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PixelGrid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pixel1 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel1, 50);
    lv_obj_set_height(ui_Pixel1, 50);
    lv_obj_set_align(ui_Pixel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel2 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel2, 50);
    lv_obj_set_height(ui_Pixel2, 50);
    lv_obj_set_align(ui_Pixel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel3 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel3, 50);
    lv_obj_set_height(ui_Pixel3, 50);
    lv_obj_set_align(ui_Pixel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel4 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel4, 50);
    lv_obj_set_height(ui_Pixel4, 50);
    lv_obj_set_align(ui_Pixel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel5 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel5, 50);
    lv_obj_set_height(ui_Pixel5, 50);
    lv_obj_set_align(ui_Pixel5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel6 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel6, 50);
    lv_obj_set_height(ui_Pixel6, 50);
    lv_obj_set_align(ui_Pixel6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel7 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel7, 50);
    lv_obj_set_height(ui_Pixel7, 50);
    lv_obj_set_align(ui_Pixel7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel8 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel8, 50);
    lv_obj_set_height(ui_Pixel8, 50);
    lv_obj_set_align(ui_Pixel8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel9 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel9, 50);
    lv_obj_set_height(ui_Pixel9, 50);
    lv_obj_set_align(ui_Pixel9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel10 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel10, 50);
    lv_obj_set_height(ui_Pixel10, 50);
    lv_obj_set_align(ui_Pixel10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel11 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel11, 50);
    lv_obj_set_height(ui_Pixel11, 50);
    lv_obj_set_align(ui_Pixel11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel12 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel12, 50);
    lv_obj_set_height(ui_Pixel12, 50);
    lv_obj_set_align(ui_Pixel12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel13 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel13, 50);
    lv_obj_set_height(ui_Pixel13, 50);
    lv_obj_set_align(ui_Pixel13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel14 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel14, 50);
    lv_obj_set_height(ui_Pixel14, 50);
    lv_obj_set_align(ui_Pixel14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel14, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel15 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel15, 50);
    lv_obj_set_height(ui_Pixel15, 50);
    lv_obj_set_align(ui_Pixel15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel16 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel16, 50);
    lv_obj_set_height(ui_Pixel16, 50);
    lv_obj_set_align(ui_Pixel16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel17 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel17, 50);
    lv_obj_set_height(ui_Pixel17, 50);
    lv_obj_set_align(ui_Pixel17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel18 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel18, 50);
    lv_obj_set_height(ui_Pixel18, 50);
    lv_obj_set_align(ui_Pixel18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel18, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel19 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel19, 50);
    lv_obj_set_height(ui_Pixel19, 50);
    lv_obj_set_align(ui_Pixel19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel19, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel20 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel20, 50);
    lv_obj_set_height(ui_Pixel20, 50);
    lv_obj_set_align(ui_Pixel20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel20, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel21 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel21, 50);
    lv_obj_set_height(ui_Pixel21, 50);
    lv_obj_set_align(ui_Pixel21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel21, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel22 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel22, 50);
    lv_obj_set_height(ui_Pixel22, 50);
    lv_obj_set_align(ui_Pixel22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel22, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel23 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel23, 50);
    lv_obj_set_height(ui_Pixel23, 50);
    lv_obj_set_align(ui_Pixel23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel23, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel24 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel24, 50);
    lv_obj_set_height(ui_Pixel24, 50);
    lv_obj_set_align(ui_Pixel24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel24, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel25 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel25, 50);
    lv_obj_set_height(ui_Pixel25, 50);
    lv_obj_set_align(ui_Pixel25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel25, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel26 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel26, 50);
    lv_obj_set_height(ui_Pixel26, 50);
    lv_obj_set_align(ui_Pixel26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel26, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel27 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel27, 50);
    lv_obj_set_height(ui_Pixel27, 50);
    lv_obj_set_align(ui_Pixel27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel27, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel28 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel28, 50);
    lv_obj_set_height(ui_Pixel28, 50);
    lv_obj_set_align(ui_Pixel28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel29 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel29, 50);
    lv_obj_set_height(ui_Pixel29, 50);
    lv_obj_set_align(ui_Pixel29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel29, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel29, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel30 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel30, 50);
    lv_obj_set_height(ui_Pixel30, 50);
    lv_obj_set_align(ui_Pixel30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel30, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel31 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel31, 50);
    lv_obj_set_height(ui_Pixel31, 50);
    lv_obj_set_align(ui_Pixel31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel31, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel32 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel32, 50);
    lv_obj_set_height(ui_Pixel32, 50);
    lv_obj_set_align(ui_Pixel32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel32, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel33 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel33, 50);
    lv_obj_set_height(ui_Pixel33, 50);
    lv_obj_set_align(ui_Pixel33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel33, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel34 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel34, 50);
    lv_obj_set_height(ui_Pixel34, 50);
    lv_obj_set_align(ui_Pixel34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel34, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel35 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel35, 50);
    lv_obj_set_height(ui_Pixel35, 50);
    lv_obj_set_align(ui_Pixel35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel35, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel35, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel36 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel36, 50);
    lv_obj_set_height(ui_Pixel36, 50);
    lv_obj_set_align(ui_Pixel36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel36, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel36, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel37 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel37, 50);
    lv_obj_set_height(ui_Pixel37, 50);
    lv_obj_set_align(ui_Pixel37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel37, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel37, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel38 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel38, 50);
    lv_obj_set_height(ui_Pixel38, 50);
    lv_obj_set_align(ui_Pixel38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel38, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel38, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel39 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel39, 50);
    lv_obj_set_height(ui_Pixel39, 50);
    lv_obj_set_align(ui_Pixel39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel39, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel39, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel40 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel40, 50);
    lv_obj_set_height(ui_Pixel40, 50);
    lv_obj_set_align(ui_Pixel40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel40, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel40, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel41 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel41, 50);
    lv_obj_set_height(ui_Pixel41, 50);
    lv_obj_set_align(ui_Pixel41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel41, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel41, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel41, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel42 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel42, 50);
    lv_obj_set_height(ui_Pixel42, 50);
    lv_obj_set_align(ui_Pixel42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel42, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel42, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel42, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel43 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel43, 50);
    lv_obj_set_height(ui_Pixel43, 50);
    lv_obj_set_align(ui_Pixel43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel43, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel43, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel43, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel44 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel44, 50);
    lv_obj_set_height(ui_Pixel44, 50);
    lv_obj_set_align(ui_Pixel44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel44, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel44, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel45 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel45, 50);
    lv_obj_set_height(ui_Pixel45, 50);
    lv_obj_set_align(ui_Pixel45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel45, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel45, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel46 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel46, 50);
    lv_obj_set_height(ui_Pixel46, 50);
    lv_obj_set_align(ui_Pixel46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel46, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel46, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel47 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel47, 50);
    lv_obj_set_height(ui_Pixel47, 50);
    lv_obj_set_align(ui_Pixel47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel47, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel47, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel48 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel48, 50);
    lv_obj_set_height(ui_Pixel48, 50);
    lv_obj_set_align(ui_Pixel48, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel48, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel48, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel49 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel49, 50);
    lv_obj_set_height(ui_Pixel49, 50);
    lv_obj_set_align(ui_Pixel49, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel49, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel49, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel49, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel50 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel50, 50);
    lv_obj_set_height(ui_Pixel50, 50);
    lv_obj_set_align(ui_Pixel50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel50, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel50, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel51 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel51, 50);
    lv_obj_set_height(ui_Pixel51, 50);
    lv_obj_set_align(ui_Pixel51, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel51, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel51, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel51, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel52 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel52, 50);
    lv_obj_set_height(ui_Pixel52, 50);
    lv_obj_set_align(ui_Pixel52, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel52, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel52, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel52, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel52, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel53 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel53, 50);
    lv_obj_set_height(ui_Pixel53, 50);
    lv_obj_set_align(ui_Pixel53, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel53, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel53, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel53, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel53, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel54 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel54, 50);
    lv_obj_set_height(ui_Pixel54, 50);
    lv_obj_set_align(ui_Pixel54, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel54, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel54, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel54, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel54, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel55 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel55, 50);
    lv_obj_set_height(ui_Pixel55, 50);
    lv_obj_set_align(ui_Pixel55, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel55, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel55, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel55, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel55, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel56 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel56, 50);
    lv_obj_set_height(ui_Pixel56, 50);
    lv_obj_set_align(ui_Pixel56, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel56, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel56, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel56, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel56, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel57 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel57, 50);
    lv_obj_set_height(ui_Pixel57, 50);
    lv_obj_set_align(ui_Pixel57, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel57, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel57, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel57, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel57, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel58 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel58, 50);
    lv_obj_set_height(ui_Pixel58, 50);
    lv_obj_set_align(ui_Pixel58, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel58, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel58, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel58, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel58, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel59 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel59, 50);
    lv_obj_set_height(ui_Pixel59, 50);
    lv_obj_set_align(ui_Pixel59, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel59, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel59, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel59, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel59, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel60 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel60, 50);
    lv_obj_set_height(ui_Pixel60, 50);
    lv_obj_set_align(ui_Pixel60, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel60, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel60, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel60, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel61 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel61, 50);
    lv_obj_set_height(ui_Pixel61, 50);
    lv_obj_set_align(ui_Pixel61, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel61, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel61, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel61, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel61, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel62 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel62, 50);
    lv_obj_set_height(ui_Pixel62, 50);
    lv_obj_set_align(ui_Pixel62, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel62, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel62, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel62, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel62, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel63 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel63, 50);
    lv_obj_set_height(ui_Pixel63, 50);
    lv_obj_set_align(ui_Pixel63, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel63, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel63, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel63, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel63, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pixel64 = lv_btn_create(ui_PixelGrid);
    lv_obj_set_width(ui_Pixel64, 50);
    lv_obj_set_height(ui_Pixel64, 50);
    lv_obj_set_align(ui_Pixel64, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pixel64, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pixel64, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pixel64, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pixel64, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleCamera = lv_label_create(ui_ScreenCamera);
    lv_obj_set_width(ui_TitleCamera, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleCamera, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleCamera, 0);
    lv_obj_set_y(ui_TitleCamera, 10);
    lv_obj_set_align(ui_TitleCamera, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TitleCamera, "Heat Image of IR Camera ");
    lv_obj_set_style_text_font(ui_TitleCamera, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

}
