// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT ButtonMinus

lv_obj_t * ui_ButtonMinus_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ButtonMinus;
    cui_ButtonMinus = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_ButtonMinus, 36);
    lv_obj_set_height(cui_ButtonMinus, 36);
    lv_obj_set_align(cui_ButtonMinus, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ButtonMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ButtonMinus, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ButtonMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTONMINUS_NUM);
    children[UI_COMP_BUTTONMINUS_BUTTONMINUS] = cui_ButtonMinus;
    lv_obj_add_event_cb(cui_ButtonMinus, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ButtonMinus, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ButtonMinus_create_hook(cui_ButtonMinus);
    return cui_ButtonMinus;
}

