// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_BUTTONMINUS_H
#define _UI_COMP_BUTTONMINUS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ButtonMinus
#define UI_COMP_BUTTONMINUS_BUTTONMINUS 0
#define _UI_COMP_BUTTONMINUS_NUM 1
lv_obj_t * ui_ButtonMinus_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
